### ISSUE TITLE
'promote' from local directory

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#10]
As a developer (or Task in a Pipeline, etc) I need to be able to say, `promote service-name from/path/to/local/git/repo --to https://remote.git.repo` 

Either `--from` needs to take a directory path as well as https:// urls, or we need a different CLI argument. I'd prefer the former but could accept the latter.

**Comment by bigkevmcd** [comment]
I _think_ this will be supported, given that the path will be passed to git, and git supports doing something like `git clone ~/mygitrepo mynewgitrepo`

**Comment by mnuttall** [comment]
@bigkevmcd also writes, 
> 'there's a bit of code that takes the URL you provide, and supplements it with credentials. but, it's delegated to a function so, it would be easy enough to look at the protocol in there, and if it's not "https", don't do anything. so, the "url" you provided would get passed through directly to git.'

**Comment by bigkevmcd** [comment]
This is the logic I'm referering to https://github.com/rhd-gitops-example/services/blob/master/pkg/avancement/service_manager.go#L150
