### ISSUE TITLE
Update automerge-example to v1beta1

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#101]
Further to https://github.com/rhd-gitops-example/services/issues/55, add support for Tekton `v1beta1` APIs to  `automerge-example`, splitting the sample into `v1alpha1` and `v1beta1` directories, and removing all PipelineResources from the `v1beta1` version. Hopefully the changes made in https://github.com/rhd-gitops-example/services/pull/97 will be largely applicable to this second sample.

**Comment by a-roberts** [comment]
PR is in so let's close this
