### ISSUE TITLE
Support URLs with credentials on

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#11]
Accept URLs of the form, `https://username@github.com/username/repository.git` and `https://username:password@github.com/username/repository.git`. Don't prompt for username or password if they have all ready been provided. 

More often than not, 'password' should be a token, and 'username' won't matter.

**Comment by dibbles** [comment]
After talking with Kevin, we believe he already implemented this and indeed there are tests:
https://github.com/rhd-gitops-example/services/blob/612aa6abe3514490b43c9d352bf3a04e5faf3c91/pkg/avancement/service_manager_test.go#L63

I've tested manually and it seems to function (just don't make the mistake of trying to use a password for an account where 2FA is enabled - it wont work!)

@mnuttall is anymore needed than the following already present code, which adds a "promotion" user and the environment github token to the remote URL if it doesn't already contain a user in the case https URLs:

https://github.com/rhd-gitops-example/services/blob/612aa6abe3514490b43c9d352bf3a04e5faf3c91/pkg/avancement/service_manager.go#L182

**Comment by mnuttall** [comment]
Closing this since it looks like we have the function and test coverage that we need.
