### ISSUE TITLE
Promote more than one service at a time?

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#13]
Discuss: consider extending cli to permit promoting more than one service in a single PR. (e.g. new service-a depends on new service-b.)

**Comment by bigkevmcd** [comment]
Is this "promoting an application"?

**Comment by mnuttall** [comment]
I wish I'd written down more information about who wanted this any why!

**Comment by mnuttall** [comment]
Closing this until we remember why we thought it necessary.
