### ISSUE TITLE
`promote` services from and to a directory, `services`

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#2]
A sample gitops directory structure can be found in https://github.com/mnuttall/gitops-repo-testing. (This should itself be cleaned up and moved into the rhd-gitops-example org.) 

Commands such as 
```
services promote \
 --from https://github.com/mnuttall/gitops-repo-testing \
 --to   https://github.com/mnuttall/staging \
 --service services/service-a
```
creates a PR like https://github.com/mnuttall/staging/pull/1/files in which the copied files in under a root directory, 'service-a'. 

What we want instead is for `promote --service service-a` to effectively `cp -R services/service-a` from the source to the target repository. 

This enforces a convention that services are in a directory called 'services'. That's ok. 

See also https://github.com/rhd-gitops-example/services#running - these docs need fixing. 

The `CopyService()` function in https://github.com/rhd-gitops-example/services/blob/master/pkg/git/copy.go , called from https://github.com/rhd-gitops-example/services/blob/7bf45bed6c888c0819dec9d9d95f45e941e60d68/pkg/avancement/service_manager.go#L54-L64, will need a tweak.

**Comment by akihikokuroda** [comment]
The command is only this form for now?
```
promote service-a --from https://my/dev.git --to https://my/staging.git
```
because of 
`
After some prototyping, separating each environment into its own repository is believed to be the most appropriate design choice. 
`
?
Another question:
Is the `promote` a command of cli `service`?

**Comment by mnuttall** [comment]
^^ Hi @akihikokuroda yes, it's only between repositories at this point. Yes, `promote` is a command of `service` as per the updated description of this issue.
