### ISSUE TITLE
Delete local cache by default

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#20]
After one call to promote, it is necessary to `rm -rf ~/.promotion/cache` before the next. Modify the CLI so that the cache is deleted by default. Add a `--keep` flag to prevent cache deletion.

**Comment by bigkevmcd** [comment]
Add a `Remove() error` method to the `Repository` and trigger it at the end of the `Promote` method.

Inside `Remove()`, use https://golang.org/pkg/os/#RemoveAll to delete the tree.

**Comment by dibbles** [comment]
I'll take a look at doing this.

**Comment by dibbles** [comment]
This can be closed by someone with relevant powers. @mnuttall @bigkevmcd
