### ISSUE TITLE
New branch by default for new pull requests

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#21]
Each promotion PR needs its own branch. The CLI user should not be required to specify `--branch [new branch]` on each request. If --branch is not specified, a temporary, unique branch should be created.

**Comment by Megan-Wright** [comment]
I'll pick this one up :)

**Comment by mnuttall** [comment]
test - @Megan-Wright

**Comment by bigkevmcd** [comment]
You could maybe do a "head" on the source branch, and use that as **part** of the generated branch name?

Essentially, extend `git.Repository` with `Head() (string, error)` and have it execute and return the result of `git rev-parse --short HEAD`.

**Comment by bigkevmcd** [comment]
The above suggestion could fail with many off the same root branch.

You could add some UUID generated randomness on the end (maybe 5 chars would be enought?)

**Comment by mnuttall** [comment]
In Slack we discussed naming branches [source-repo-name]-[short git commit]-[short uuid, maybe 5-ish characters]. 

We could look at replacing the [random] section with a date or timestamp that would make branch names sortable nicely, but those timestamps would be quite long. Let's go for the [short random] option for now and see how it looks.

**Comment by mnuttall** [comment]
Hi @Megan-Wright can we close this now that https://github.com/rhd-gitops-example/services/pull/32 is merged?
