### ISSUE TITLE
Should --debug be a global or command specific option?

### ISSUE THREAD

**Issue by a-roberts** [rhd-gitops-example/services#27]
```
(base) Adams-MBP:services aroberts$ ./services --debug promote --from https://github.com/a-roberts/gitops-repo-testing --to https://github.com/a-roberts/staging --service service-a 
2020/03/31 11:27:59 fatal: destination path 'gitops-repo-testing' already exists and is not an empty directory.

(base) Adams-MBP:services aroberts$ ./services promote --from https://github.com/a-roberts/gitops-repo-testing --to https://github.com/a-roberts/staging --service service-a --debug
Incorrect Usage: flag provided but not defined: -debug

NAME:
   services promote - promote from one environment to another

USAGE:
   services promote [command options] [arguments...]

OPTIONS:
   --from value          source Git repository
   --to value            destination Git repository
   --service value       service name to promote
   --branch-name value   the name to use for the newly created branch (default: "test-branch")
   --cache-dir value     where to cache Git checkouts (default: "~/.promotion/cache")
   --commit-name value   the name to use for commits when creating branches [$COMMIT_NAME]
   --commit-email value  the email to use for commits when creating branches [$COMMIT_EMAIL]
   --help, -h            show help (default: false)
   
2020/03/31 11:31:28 flag provided but not defined: -debug
```

You can see I had to provide it at globally (so at the top level, ./services --debug) and this means I can't stick it on the end. There's been good discussion in Slack when I raised this (so @bigkevmcd and @mnuttall, lemme know if I'm misquoting you or I've missed something important!).

Kevin suggested we could move to using `cobra` (I think that's an aside), and even provided the change we'd want to make (so at the time of this issue - simply from the global to promote flag list): 
https://github.com/rhd-gitops-example/services/blob/master/cmd/services/main.go#L37 to https://github.com/rhd-gitops-example/services/blob/master/cmd/services/main.go#L85

so I think this makes for a useful first issue for somebody if we did want to make it so.

**Comment by Megan-Wright** [comment]
I'll have a go at making this a promote flag instead

**Comment by bigkevmcd** [comment]
Yeah, moving to cobra would be a bit more of a change (not a huge one) and I'm not convinced it'd be any easier to understand the flags bit, but, more folks are probably familiar with cobra :-)

**Comment by a-roberts** [comment]
Merged so let's close this one, thanks all
