### ISSUE TITLE
Remove unused yaml from sample

### ISSUE THREAD

**Issue by dibbles** [rhd-gitops-example/services#37]
The sample in the docs directory contains a number of yaml files which are not required.  Remove these files.

**Comment by dibbles** [comment]
@akihikokuroda : the sample does not document making use of promote.yaml and promoterun.yaml.  From looking at all the files together is the samples deigned such that you use servicepromotepipelinerun to promote from a build into the test gitops repo and then use the promoterun to promote from test to prod ?

If so I will get that added/modified in the docs.

**Comment by akihikokuroda** [comment]
Yes, they are.  Thanks!

**Comment by dibbles** [comment]
docs update under #43
