### ISSUE TITLE
Travis build for services

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#4]
In the first instance we need to `go build` and `go test` on PullRequests and merges. Travis is the simplest way to get this up and working.

**Comment by a-roberts** [comment]
Yeah big +1 on this, so I'm guessing only an owner (would that big @bigkevmcd only?) can do this?

https://travis-ci.org/ steps seem straight-forward enough, we've used Travis plenty here at IBM before so happy to volunteer to do this

Official docs suggest it could be as easy as augmenting our existing .travis.yaml with

```
script: go test -v ./...
```

🤞

**Comment by bigkevmcd** [comment]
I think this is already done?

See the badge in the README for a link to the Travis tests :-)

**Comment by a-roberts** [comment]
@bigkevmcd you're so right, @mnuttall as well, let's close this 😄
