### ISSUE TITLE
Builds should be published?

### ISSUE THREAD

**Issue by dibbles** [rhd-gitops-example/services#40]
Builds of each integration should be published somewhere official? Might be something for @bigkevmcd and @mnuttall to discuss depending on the future of this code

- will it be integrated with odo or standalone?
- does it need a short term home whilst things are decided?

**Comment by mnuttall** [comment]
Short term home is `quay.io/redhat-developer/gitops-cli`. 
Longer-term home depends on https://github.com/openshift/odo/pull/2733
