### ISSUE TITLE
Cache isn't cleared when a promote command fails

### ISSUE THREAD

**Issue by Megan-Wright** [rhd-gitops-example/services#48]
# Expected Behaviour
When I run a promote command which fails, if I then amend this to a promote command which should pass and try to rerun it, I expect it to work without error.

# Actual Behaviour
After a failed promote command, any new promote command (whether valid or not) will fail because the cache hasn't been cleared, and so I have to run `rm -rf ~/.promotion/cache;` before subsequent promote commands.

# Steps to Reproduce
Run a promote command which will  fail, such as adding invalid characters to the branch name, and then immediately rerun the same promote command in a way which should work.

**Comment by bigkevmcd** [comment]
This is caused by this https://github.com/rhd-gitops-example/services/blob/master/pkg/avancement/service_manager.go#L102

(And the same logic for the destination)

The cache is only deferred for removal, if creating it does not error.

If the Cache checkout fails, it doesn't clean up.

**Comment by Megan-Wright** [comment]
Tried reproducing this one this morning and it seems to have been fixed while I was on holiday? not sure where but it's all working fine now
