### ISSUE TITLE
Simplify Tekton example

### ISSUE THREAD

**Issue by a-roberts** [rhd-gitops-example/services#53]
I'm going through it now and it's particularly clunky but can easily be improved - I'd rather set a bunch of variables once, have the variables be passed through to the yaml (under a `templates` folder perhaps), and be good to go - or simply move everything I need to apply to be under the one folder (instead of `docs`) and everything to change goes in another.

One fancy approach would be to have a bash script, a variables file, and then do some sedding instead of having users replace `xxx` in six files.

Tidy the documentation up and make it as short, clean, and, in one go, `kubectl apply`able as possible, perhaps using tkn

**Comment by mnuttall** [comment]
I looked at being able to `tkn pipeline start` but we have a Tekton Beta workspace in our PipelineRun, and I couldn't see how to make `tkn` version 0.8 bind it. Hopefully I was overlooking something.

**Comment by a-roberts** [comment]
The remaining step here is to use `tkn`, I'll create a small follow-on issue for that for anyone to pick up as the bulk of the work is now done. @Megan-Wright has the command so it should just be a case of replacing the creation of the PipelineRun steps.
