### ISSUE TITLE
CLI binaries for download

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#57]
As well as building a docker image, we would like to make the `services` binary available for download. Ideally we'd like binaries for Linux, Mac and Windows. Can we get Travis to build and publish them back to GitHub as downloads for a release? 

(i.e. push a tag to GitHub, create a release, Travis release plugin publishes artifacts.)

**Comment by ianpartridge** [comment]
You might like to look at GitHub Actions for this: https://github.com/actions/upload-release-asset

**Comment by a-roberts** [comment]
I'll have a look at this one, thanks @ianpartridge - sounds like a good avenue to explore. I do wonder if there are any other non-technical considerations we have to take into account before "publishing" them as is (just standalone binaries) onto GitHub, would be nice to have those all procedures all arranged and in place first.

I'll do some prototyping anyway just to get the binaries being produced now so we can pick 'em up for testing.

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/80005239-37509480-84bb-11ea-97c4-4ca2690e1b15.png)

Got this so far (so combining GitHub actions with the deploy Travis promote business), bumped to pick up Go 1.14 too, I'll add Windows and Mac next complete with sensible file names.

The convention at the moment (straight from the example) is when a tag is published starting with `v`, a release is made with that commit message (from the last commit on the tag) and the binary is built from that. @bigkevmcd @mnuttall any thoughts on this?
