### ISSUE TITLE
Tekton prototyping

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#6]
We need to embed the `promote` cli in a Tekton task. A typical pipeline should be, 
- docker build
- docker tag
- docker push 
- promote [newly built image] [into dev]

Build a Tekton Task and Pipeline that does this, and demonstrate it back to the team.

**Comment by akihikokuroda** [comment]
The files for this are in this PR https://github.com/rhd-gitops-example/services/pull/35.
