### ISSUE TITLE
Publish Docker images on release. Cut a v0.1 release. 

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#66]
We currently publish binaries in our release process, but we also need to publish docker images. 

Work with RedHat to establish whether we can publish specifically tagged images to quay.io from our travis.yml, or whether a different mechanism is required.

**Comment by a-roberts** [comment]
@bigkevmcd any pointers? Thinking we'll provide some creds in the Travis job somewhere and go from there, I'd be happy to run with this but I'm wondering what the process atm is...a manual cranking of the wheel? 😆
