### ISSUE TITLE
Use exemplar projects in Tekton example (dev, staging, prod)

### ISSUE THREAD

**Issue by a-roberts** [rhd-gitops-example/services#68]
With the improvements made at https://github.com/rhd-gitops-example/services/pull/65, we're still referencing contributor's repositories - worse still, the example repositories don't conform to our GitOps structure. So we end up Docker building them when surely that isn't what we want. Ideally, you'd just need

https://github.com/rhd-gitops-example/gitops-example-dev
https://github.com/rhd-gitops-example/gitops-example-staging
and a third repository, https://github.com/rhd-gitops-example/gitops-example-prod.

Under this issue, modify the example to use these pipelines successfully - building and pushing the code to Dockerhub for example).

We currently reference 

- https://github.com/a-roberts/gitops-repo-testing
- https://github.com/akihikokuroda/promote-demo
- https://github.com/akihikokuroda/gitops-test

While these are fine to be forked for testing, let's have something more official.

**Comment by mnuttall** [comment]
I think this has now been done under https://github.com/rhd-gitops-example/services/issues/70.
