### ISSUE TITLE
Modify example repositories for /environments/env-name/ structure

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#78]
Further to https://github.com/rhd-gitops-example/services/issues/72 our sample gitops repositories https://github.com/a-roberts/gitops-example-dev and https://github.com/a-roberts/gitops-example-staging  need to be updated with top-level paths `/environments/dev` and `environments/staging` respectively.

**Comment by a-roberts** [comment]
I remember merging the two PRs for the example repositories (so, from GitOps repository to GitOps repository - staging to dev), we now just have the promote-demo referring to an individual contributor's repository - 

```
For the repository to promote from, an example can be forked from here: https://github.com/akihikokuroda/promote-demo
```

@mnuttall follow-up issue or a potentially quick one by yourself as part of this?
