### ISSUE TITLE
README overhaul

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#79]
- Split a DEVELOPMENT.md out of the readme. 
- Introduce the tool, link to documention of the repository structure - currently that's available under https://github.com/rhd-gitops-example/manifest-documentation#configuring-services 
- Document where to get the cli binary from, and what its options do
- Be careful to differentiate the options in `--from` between local and remote cases.

**Comment by a-roberts** [comment]
Under this item should we also include a `docker run` example? On the main readme I don't see this but we've got published images somewhere surely for our stakeholders to pick up

**Comment by mnuttall** [comment]
The docker images currently support the CLI in our Tekton samples. I'll added a note about where the images reside in `quay.io`. I hadn't thought about `docker run` as a use case. Maybe it's a way of supporting Windows?

**Comment by mnuttall** [comment]
Closed by https://github.com/rhd-gitops-example/services/pull/88
