### ISSUE TITLE
Test `services` as an `oc` plugin

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#80]
@bigkevmcd writes, 
> oc has been released with plugin support
> so, if you were to rename the `cmd/services` to `cmd/oc-services` or symlink it or do something else you'd have a plugin

Test this out! Does `oc` add any value to running `services` either in a docker container on the command line?

**Comment by a-roberts** [comment]
I'll give this a try

**Comment by a-roberts** [comment]
Got the binary picked up fine, docs at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/cli_tools/openshift-cli-oc were useful (so indeed, rename and chmod, invoke with `oc services`), I'll kick the tires tomorrow and see if anything's different

**Comment by a-roberts** [comment]
The normal flow (so doing `oc services promote`) is working perfectly fine, I'm experimenting with a Dockerfile atm sitting in a `plugin` directory I've made that basically grabs an oc binary (the latest 4.3 currently), builds our services binary but with a `oc-services` name, and then makes the entrypoint in the Dockerfile be `oc services` - for testing things out.

**Comment by a-roberts** [comment]
Wrapping things up for today but I'm having trouble getting the git commit to work with my docker run atm (so I'm providing my token, --commit-name and --commit-email as well as the usual from/to/service name args). Consistently get the classic 128 error and if I print the author, args, and envFromAuthor and repoPath, those all look good.

Will continue debugging tomorrow.

**Comment by a-roberts** [comment]
Made some progress on this today, interestingly I have to make modifications to our services code such that we do two `git config` commands (to set the name and email), or the `git commit ` command fails in the container (complaining I need to set user.name - despite my  command having `--commit-name` and `--commit-email` all set), suggesting the existing way of doing things doesn't result in the settings being passed to the underlying git command invocation.

With my changes now, a PR is made successfully using:
```
docker run -e GITHUB_TOKEN=<mytoken> adamroberts/oc-services-plugin-experiment:latest services promote --from https://github.com/a-roberts/gitops.git --to https://github.com/a-roberts/gitops-target.git --service promote-demo --commit-name=a-roberts --commit-email=aroberts@uk.ibm.com
```

no observable differences to mention.

I'll try this in a Tekton Pipeline next, so looks like we don't get any particular value but it does expose one potential issue.

You can see what I've got at https://github.com/a-roberts/services/tree/pluginexperiment/plugin.
