### ISSUE TITLE
services promote does not create PRs for repos in orgs

### ISSUE THREAD

**Issue by kvijai82** [rhd-gitops-example/services#81]
When I try to do a `services promote` command to promote to a gitops repo that's in an org, the command fails with the following error:

2020/05/15 13:49:55 failed to create a pull-request for branch workspace-git-source-local-dir-838ea, error: Not Found. repository URL = https://github.ibm.com/kabanero-org-test/test1-gitops

It creates the branch with the expected updates but does not create the PR.  I gave my token pretty much all possible access.

**Comment by a-roberts** [comment]
Tried this today using my own org on GitHub (so not GHE), the missing .git on the end is likely the problem - here's my investigation

```
services promote --from promote-demo --to https://github.com/a-roberts-test-org/gitops-example-dev --service promote-demo
```

With some debug I see

```
(base) Adams-MBP:~ aroberts$ services promote --from promote-demo --to https://github.com/a-roberts-test-org/gitops-example-dev --service promote-demo
in promote
in cloneRepo
repoURL in cloneRepo: https://promotion:(thetoken)@github.com/a-roberts-test-org/gitops-example-dev
Doing the clone on repo url https://promotion:(thetoken)@github.com/a-roberts-test-org/gitops-example-dev
path to use: a-roberts-test-org/gitops-example
```

Notice the incorrect path to use. This is coming from

```
	u, _ := url.Parse(toURL)
	// take out ".git" at the end
	pathToUse := u.Path[1 : len(u.Path)-4]
	fmt.Printf("path to use: %s\n", pathToUse)
	pr, _, err := client.PullRequests.Create(ctx, pathToUse, prInput)
	fmt.Printf("prInput: %s\n", prInput)
	fmt.Printf("pr: %+v\n", pr)
	return pr, err
```

in service_manager.go. 

I want it to use gitops-example-dev though - gitops-example isn't a thing. If I add .git on the end, all is good, see https://github.com/a-roberts-test-org/gitops-example-dev/pull/1

@kvijai82 Vijai can you try with .git on the end please? We can add some validation on our end for the inputs next if that's all good

**Comment by a-roberts** [comment]
```
(base) Adams-MBP:gitops aroberts$ services promote --from promote-demo --to https://github.com/a-roberts-test-org/gitops-example-dev --service promote-demo
Not stripping
Creating a PR with URL: a-roberts-test-org/gitops-example-dev
2020/05/19 10:34:53 created PR 2
(base) Adams-MBP:gitops aroberts$ services promote --from promote-demo --to https://github.com/a-roberts-test-org/gitops-example-dev.git --service promote-demo
Stripping .git from the end to determine path
Creating a PR with URL: a-roberts-test-org/gitops-example-dev
2020/05/19 10:35:07 created PR 3

```

Implementation is fine, adding a test next then I'll do a PR so this works with and without .git suffixes
