### ISSUE TITLE
Promote within a repository

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#92]
`promote` currently relies on `--from` and `--to` being different. The repository spec permits `/environments/ `to contain more than one directory. Promotion between environments governed within a single repository should be possible. 

The `--from` argument can all ready be either a URL of a git repository, or a local path. We could overload it further with syntax of the form, 

```
promote --from dev --to staging --within https://my.git.repo
```

Work with @bigkevmcd to thrash out the right syntax for this form of the command. 

As written, this issue only addresses promotion _within_ a 'type-1' repository. It does not address promotion between 'type-1' and 'type-3' repositories. We may need a decision on whether this is possible, or desirable, as part of the CLI syntax decision.

**Comment by JustinKuli** [comment]
I'm interested in working on this one, if nobody else has claimed it

**Comment by JustinKuli** [comment]
I met with @bigkevmcd to talk about syntax, we discussed a few options but didn't make a final decision. Before diving in on the possibilities, I want to make sure I have the background right and we're on the same page.

In the original design there were three "options" for the repository layouts:
1. One repository managing multiple environments, in different directories on a single branch
2. One repository managing multiple environments, each on a different branch
3. Many repositories each managing a single environment

Up to now, the functionality here has been limited to option 3. The `--from` and `--to` parameters specify the URLs of the different repositories. Work on this issue would open up support for option 1. Exposing options for branches (#106) would open support for option 2.

A) My first thought was to just add `--from-env` and `--to-env` parameters. I think the advantage of this is simplicity in the code (just add new stuff) and not overloading any current parameters (`--from` and `--to` would always just be repository URLs). However, having too many options might not make a good user experience.

B) Mark's suggestion overloads the `--from` and `--to` parameters, which shifts the complexity to the code. It's certainly possible to handle it there: basically if `--within` is given, then we could understand that the `--from` and `--to` parameters refer to sub-directories under "environments/" in the repository, and are no longer URLs. There are fewer parameters in this plan, but I worry that it will be less discoverable for the user: the "help" output for `--for` would have to say that it is either a Git repository URL, or it's an environment (or, it's the local path).

C) @bigkevmcd suggested splitting the command into new subcommands. Most obviously, the 'local' flow really seems like it could be separated from the other promote flows. I'm not totally clear on what he imagined these looking like, these are just placeholders for now:
- `services promote add <--service> <--to> [--to-branch] [--to-env]` ("local" flow)
- `services promote within <--service> <--repo> <--from> <--to>` (option 1, specify env folders)
- `services promote branch <--service> <--repo> <--from> <--to>` (option 2, specify branches)
- `services promote across <--service> <--from> <--to>` (option 3, specify repo URLs)

In all of these, we can have global options for credentials, commit details, keep-cache, etc.

**Comment by mnuttall** [comment]
I'm torn between option a) --from-env / --to-env, and the option c) approach of introducing sub-commands. I think overloading --from and --to is bad: --from already confuses people in that it can be a local path, or a URL. Option a) doesn't fix that. 

I wonder if the refactor of https://github.com/rhd-gitops-example/services/issues/104 could be combined with option c) to split local promotion out into a subcommand, and refactor the code around local at the same time.

**Comment by JustinKuli** [comment]
I did some experimenting (see #108) around subcommands and things seem to work pretty well. The basic approach is to have the actual `Promote` function support any branch/repo/folder combination, and let the CLI expose more restricted options (for example, a subcommand that only lets you promote between branches in the same repository). It would then be easy to combine this with a refactor for "local", and have another subcommand with all the options exposed.

It sounds like there isn't much love for option B. I think A and C can be combined easily if there is a subcommand exposing all of the options. I'll get that ready for a real PR. I think the main thing to still be figured out is the names for the subcommands, especially the one exposing all of the options.

**Comment by mnuttall** [comment]
Closed by https://github.com/rhd-gitops-example/services/pull/112
